/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;

/**
 *
 * @author TecniDEV
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContenedor = new javax.swing.JPanel();
        menuPrincipal = new javax.swing.JMenuBar();
        mnuProductos = new javax.swing.JMenu();
        menuProductosCrear = new javax.swing.JMenuItem();
        menuProductosEditar = new javax.swing.JMenuItem();
        menuProductosComprar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("C.R.U.D. NetBeans");

        javax.swing.GroupLayout panelContenedorLayout = new javax.swing.GroupLayout(panelContenedor);
        panelContenedor.setLayout(panelContenedorLayout);
        panelContenedorLayout.setHorizontalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1045, Short.MAX_VALUE)
        );
        panelContenedorLayout.setVerticalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 591, Short.MAX_VALUE)
        );

        mnuProductos.setBackground(new java.awt.Color(204, 204, 204));
        mnuProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono-compra.png"))); // NOI18N
        mnuProductos.setText("Productos");
        mnuProductos.setToolTipText("DE CLICK PARA REGISTRAR O ACTUALIZAR O ELIMINAR UN PRODUCTO");
        mnuProductos.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N

        menuProductosCrear.setText("Crear Productos");
        menuProductosCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProductosCrearActionPerformed(evt);
            }
        });
        mnuProductos.add(menuProductosCrear);

        menuProductosEditar.setText("Editar Productos");
        menuProductosEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProductosEditarActionPerformed(evt);
            }
        });
        mnuProductos.add(menuProductosEditar);

        menuProductosComprar.setText("Comprar Producto");
        menuProductosComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProductosComprarActionPerformed(evt);
            }
        });
        mnuProductos.add(menuProductosComprar);

        menuPrincipal.add(mnuProductos);

        setJMenuBar(menuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuProductosCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProductosCrearActionPerformed
        CrearProductoInternalFrame crear = new CrearProductoInternalFrame();
        cargarFormulario(crear);
    }//GEN-LAST:event_menuProductosCrearActionPerformed

    private void menuProductosEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProductosEditarActionPerformed
        EditarProductoInternalFrame editar = new EditarProductoInternalFrame();
        cargarFormulario(editar);
    }//GEN-LAST:event_menuProductosEditarActionPerformed

    private void menuProductosComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProductosComprarActionPerformed
        FormularioCompraProductoInternalFrame crear = new FormularioCompraProductoInternalFrame();
        cargarFormulario(crear);
    }//GEN-LAST:event_menuProductosComprarActionPerformed

    private void cargarFormulario(JInternalFrame ventana){
        panelContenedor.removeAll();
        panelContenedor.add(ventana);
        ventana.setVisible(true);
        try {
            ventana.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        panelContenedor.updateUI();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar menuPrincipal;
    private javax.swing.JMenuItem menuProductosComprar;
    private javax.swing.JMenuItem menuProductosCrear;
    private javax.swing.JMenuItem menuProductosEditar;
    private javax.swing.JMenu mnuProductos;
    private javax.swing.JPanel panelContenedor;
    // End of variables declaration//GEN-END:variables
}
